# Generated by Django 2.2b1 on 2019-04-06 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sems', '0020_auto_20180622_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('gender', models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('contact_num', models.CharField(max_length=20, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=500, null=True)),
                ('avatar_path', models.CharField(blank=True, max_length=500, null=True)),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sems.User_type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
